### PR TITLE
Proper handling of union types when used as a typehints for route parameters

### LINKED ISSUE #219: ReflectionUnionType error
Cannot generate docs if controller parameter is a union type.

In my project I have a union type for Report system, user can report a User, Comment or a Post.
I have that solved with a `type` parameter in route, and creating a custom model binding in `RouteServiceProvider`.

Maybe I can somehow describe my types in doc-block above the method in controller?
Cause it can be string (if that a User username) or a int (if else).

### LINKED ISSUE #385: Deprecation warning
First of all many thanks for fixing the "methods" issue with v0.10.7... :)
This is a deprecation warning that started to appear recently:
```
enum_exists(): Passing null to parameter #1 ($enum) of type string is deprecated in /.../vendor/dedoc/scramble/src/Support/OperationExtensions/RequestEssentialsExtension.php on line 213
```
So this will become a problem in PHP 8.4...

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #219 
fixes #385

### CODE REVIEW

**Comment by cwray-tech** [comment]
@romalytvynenko are these changes a part of a release? I'm still getting an error due to union types.

**Comment by romalytvynenko** [comment]
@cwray-tech can you confirm you still have the issue on **0.10.12**? If so, please share the current code that fails. Thanks!

**Comment by cwray-tech** [comment]
@romalytvynenko No I was on v0.8.6.. Unfortunately, can't upgrade either due to a composer conflict. pestphp/pest-plugin-drift requires nikic/php-parser ^4.17.1 while this package requires greater than 5.

**Comment by romalytvynenko** [comment]
@cwray-tech Yeah, `0.9.0` and later versions have this breaking change. Which is the version of Laravel you're using?

**Comment by cwray-tech** [comment]
We're using laravel 10 unfortunately.

**Comment by cwray-tech** [comment]
Do you know of any work around to fix the union types issue on our end?

**Comment by romalytvynenko** [comment]
@cwray-tech Laravel 10 is supported though! 

I can see that pest drift required php-parser v5 as well: https://github.com/pestphp/pest-plugin-drift/blob/2.x/composer.json

Any chance you can try updating both dependencies?

**Comment by cwray-tech** [comment]
@romalytvynenko I removed the package and it worked. But.. running into other issues related to our app.

**Comment by romalytvynenko** [comment]
@cwray-tech let me know if you need any help!

**Pull request merged**
