### PR TITLE
Fix type error

### PR DESCRIPTION
**Pull request by soilSpoon**
I install scramble and fix the type errors that occur.

### CODE REVIEW

**Comment by romalytvynenko** [comment]
Hey @soilSpoon 

Thanks for your time and the fix.

Can you please share a code snippet that causes this error so I can reproduce the issue? 

Thanks!

**Comment by soilSpoon** [comment]
- This is a situation where CompanyLoginController inherits LoginController and uses LoginController's authenticate method.
CleanShot 2022-11-27 at 13 51 25@2x
CleanShot 2022-11-27 at 13 58 34@2x
- This is a situation where variable in closure
CleanShot 2022-11-27 at 13 52 03@2x
CleanShot 2022-11-27 at 14 03 14@2x
CleanShot 2022-11-27 at 19 02 14@2x
- This is a situation where variable in JsonResource
CleanShot 2022-11-27 at 13 56 01@2x
CleanShot 2022-11-27 at 19 05 32@2x

**Comment by romalytvynenko** [comment]
@soilSpoon can you show **your** code from the controller methods?

**Comment by soilSpoon** [comment]
The third type is the code below.
CleanShot 2022-11-28 at 12 19 02

**Comment by romalytvynenko** [comment]
Hey @soilSpoon

Thanks for the report and fixes.

For now I'm going to close this PR as these errors need fixes of the core issues behind them. As an example, to fix an error happening when you use a parent class' method as a route method, Scramble type inferring system needs rework to support classes inheritance.

Thanks again for your time!

**Pull request closed without merging**
