### PR TITLE
Added ability to override tag generation behaviour

### LINKED ISSUE #130: Add ability to customize operation tags
Right now tags are resolved based on class name and tags added to controller's class.

Give an option to customize this behavior.

### PR DESCRIPTION
**Pull request by WildEgo**
As the alternative to #282 

Closes #130

### CODE REVIEW

**Comment by romalytvynenko** [comment]
@WildEgo please fix failing tests

**Comment by WildEgo** [comment]
> @WildEgo please fix failing tests

Should be done mate, can you have a quick look?

**Comment by romalytvynenko** [comment]
@WildEgo I love the idea, but I believe the default tag resolver should not affect tests at all. Can you please fix that?

**Comment by WildEgo** [comment]
The reason it does is the following: https://swagger.io/docs/specification/grouping-operations-with-tags/
I can rollback that specific change but it's as the link above says

**Comment by romalytvynenko** [comment]
@WildEgo Please keep the original behavior.

**Comment by WildEgo** [comment]
@romalytvynenko Done

**Comment by romalytvynenko** [comment]
According the previous pr discussion, please rename the method to resolveTagsUsing and pass operation as second argument. 

Also this needs tests

**Comment by romalytvynenko** [comment]
@WildEgo any update on this?

**Comment by WildEgo** [comment]
@romalytvynenko Just updated it and synced it with the new stuff, it seems like it's having issues with different tests then mine for some reason, could you help me out with this? Rather confused atm tbh

**Comment by romalytvynenko** [comment]
@WildEgo please give me write permission to your forked repo. Cannot help without it.

**Comment by WildEgo** [comment]
> @WildEgo please give me write permission to your forked Scramble repo. Cannot help without it.

Sorry for the delay, got u there, I'm not really used to tests so this is a bit foreign for me still

**Comment by romalytvynenko** [comment]
@WildEgo still no access

image

**Comment by WildEgo** [comment]
> @WildEgo still no access
> 
> image
> 

You might have to access via email, no idea why git does that but it does

**Pull request merged**
