### PR TITLE
added support for 'multipart/form-data' in the requestBody

### PR DESCRIPTION
**Pull request by AlexSabur**
Added multipart/form-data substitution when there is a file or image rule

P.S. I know it looks clumsy. I think it will be necessary to consider supporting custom rules

### CODE REVIEW

**Comment by AlexSabur** [comment]
Damn... this is copy #222.

**Comment by romalytvynenko** [comment]
@AlexSabur Чий Крим?

**Comment by AlexSabur** [comment]
@romalytvynenko If this is important for PR. This is the territory of Ukraine

**Comment by romalytvynenko** [comment]
@AlexSabur this is important for me. 

Okay, speaking of PR.

Yeah, kind of duplicates some parts of #222, but at the same time I like how you automated request media type inference.

I suggest me merging #222 first, and then you can just open a PR with more automated request media type inference? 

Or maybe you can just push this automation on top of #222.

Or maybe you have ideas how to solve this? 😄

**Comment by AlexSabur** [comment]
> I suggest me merging https://github.com/dedoc/scramble/pull/222 first, and then you can just open a PR with more automated request media type inference?

ok, np

**Pull request merged**
